### ISSUE TITLE
Difficulty restarting/resuming training

### ISSUE THREAD

**Issue by twheatcroft07** [datajoint/element-deeplabcut#117]
Hi there,

I'm in the Sabatini lab using the sabatini-datajoint pipeline.

How does one go about restarting/resuming training a network? From what I've read ([here](https://github.com/DeepLabCut/DeepLabCut/issues/490#issuecomment-554639484)), with straight DLC, one would go into the pose config file and adjust the path to the init weights. In datajoint-dlc, do we do this also? Do we then have to insert a new training task (train.TrainingTask.insert) and then run training (train.ModelTraining.populate) ?

Thanks

**Comment by MilagrosMarin** [comment]
Hi @twheatcroft07,

Yes, just like in the DeepLabCut instructions, you'll need to edit the `pose_cfg.yml` file to point to the initialization weights from your previous training ([link](https://github.com/datajoint/element-deeplabcut/blob/c2ea14ff08ec49fb7b217db4d5b09c06111f219e/element_deeplabcut/train.py#L242)). Thanks to @CBroz1 for addressing this in the Slack channel.
